### ISSUE TITLE
I cant login and register

### ISSUE THREAD

**Issue by nonameclub** [ketanchoyal/Academic-Connect#12] opened 2020-05-02 11:40 UTC
Can you give me database structere, can you export firebase database?

**Comment by kzawadi** [comment] 2020-05-02 17:51
The Database structure is provider and very visible to-date @ketanchoyal  has updated the repo structure...to help you with the logic of login  just deal with the login flow as shown in the dbstructure folder (it contains picture of almost every steps)    and you will be able to login
Duplicate of #9

**Comment by cradlesnatcher** [comment] 2020-05-05 04:45
@nonameclub  close this issue

**Closed** 2020-05-05 15:52 UTC
